// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD97-p3mJrsvEutWa78OKvw2z1C8uMOe0k',
    appId: '1:598942334902:web:9375486f2c812eebb94b17',
    messagingSenderId: '598942334902',
    projectId: 'runnersroute-556f0',
    authDomain: 'runnersroute-556f0.firebaseapp.com',
    storageBucket: 'runnersroute-556f0.firebasestorage.app',
    measurementId: 'G-PY2H00S1TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4YI87fSs61DsIUWGdVnMXUfoEM9NfpSY',
    appId: '1:598942334902:android:bc2db7afa9fcec56b94b17',
    messagingSenderId: '598942334902',
    projectId: 'runnersroute-556f0',
    storageBucket: 'runnersroute-556f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzdFOs1Zp3rkHfd-o8zUitFySQ7jhz4n0',
    appId: '1:598942334902:ios:08ed641a2d0bff2fb94b17',
    messagingSenderId: '598942334902',
    projectId: 'runnersroute-556f0',
    storageBucket: 'runnersroute-556f0.firebasestorage.app',
    iosBundleId: 'com.example.runnersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzdFOs1Zp3rkHfd-o8zUitFySQ7jhz4n0',
    appId: '1:598942334902:ios:08ed641a2d0bff2fb94b17',
    messagingSenderId: '598942334902',
    projectId: 'runnersroute-556f0',
    storageBucket: 'runnersroute-556f0.firebasestorage.app',
    iosBundleId: 'com.example.runnersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD97-p3mJrsvEutWa78OKvw2z1C8uMOe0k',
    appId: '1:598942334902:web:54c49a0760ed95d9b94b17',
    messagingSenderId: '598942334902',
    projectId: 'runnersroute-556f0',
    authDomain: 'runnersroute-556f0.firebaseapp.com',
    storageBucket: 'runnersroute-556f0.firebasestorage.app',
    measurementId: 'G-ZKBD72WFSB',
  );
}
